name: Barrendero
main: com.alex.barrendero.BarrenderoPlugin
version: 1.2.4
api-version: "${paper.plugin.api-version}"
commands:
  barrendero:
    description: Barrendero commands
    usage: /<command> reload
    permission: barrendero.reload
permissions:
  barrendero.reload:
    description: Reload the Barrendero config
    default: op
